server:
  port: 8081

spring:
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}   # 从环境变量读取
      chat:
        options:
          model: qwen-plus             # 默认使用 qwen-max
          temperature: 0.7
          max-tokens: 2048
      retry:
        max-attempts: 20       # 默认 10，图片生成慢时不够用
        backoff:
          initial-interval: 3s # 首次轮询等待时间
          multiplier: 2        # 不要设太大，否则间隔迅速拉长
          max-interval: 15s    # 最大轮询间隔

  profiles:
    active: local


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      packages-to-scan: com.agony.springaialibaba.controller
      paths-to-match:
        - "/**"