CREATE TABLE IF NOT EXISTS sa_chat_memory
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id VARCHAR(100) NOT NULL,
    messages   TEXT         NOT NULL,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_sa_chat_memory PRIMARY KEY (id),
    CONSTRAINT uk_session UNIQUE (session_id)
);

COMMENT ON TABLE sa_chat_memory IS '对话记忆持久化';

COMMENT ON COLUMN sa_chat_memory.session_id IS '会话 ID';
COMMENT ON COLUMN sa_chat_memory.messages IS '序列化的消息列表（JSON）';